/*
 * leg7seg_display.c
 *
 *  Created on: Sep 19, 2023
 *      Author: Nhat Khai
 */

#include "led7seg_display.h"

void display7SEG0(int num) {
	switch (num) {
	case 0:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
	  	HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_SET);
	 	break;
	case 1:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_SET);
		break;
	case 2:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 4:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 5:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 6:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 7:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_SET);
		break;
	case 8:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	case 9:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_RESET);
		break;
	default:
		HAL_GPIO_WritePin(SEG_0A_GPIO_Port, SEG_0A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0B_GPIO_Port, SEG_0B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0C_GPIO_Port, SEG_0C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0D_GPIO_Port, SEG_0D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0E_GPIO_Port, SEG_0E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0F_GPIO_Port, SEG_0F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_0G_GPIO_Port, SEG_0G_Pin, GPIO_PIN_SET);
		break;
	}
}

void display7SEG1(int num) {
	switch (num) {
	case 0:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
	  	HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
	 	HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_SET);
	 	break;
	case 1:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_SET);
		break;
	case 2:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 4:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 5:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 6:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 7:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_SET);
		break;
	case 8:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	case 9:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_RESET);
		break;
	default:
		HAL_GPIO_WritePin(SEG_1A_GPIO_Port, SEG_1A_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1B_GPIO_Port, SEG_1B_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1C_GPIO_Port, SEG_1C_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1D_GPIO_Port, SEG_1D_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1E_GPIO_Port, SEG_1E_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1F_GPIO_Port, SEG_1F_Pin, GPIO_PIN_SET);
		HAL_GPIO_WritePin(SEG_1G_GPIO_Port, SEG_1G_Pin, GPIO_PIN_SET);
		break;
	}
}
